// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreWave.Data;

#nullable disable

namespace StoreWave.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("StoreWave.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic devices and gadgets",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fashion and apparel",
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Books and publications",
                            IsActive = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Home decor and garden supplies",
                            IsActive = true,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sports equipment and accessories",
                            IsActive = true,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("StoreWave.Models.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdminReply")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickedUpDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("OrderDate");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("Name");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality Bluetooth headphones with noise cancellation",
                            DiscountPrice = 119.99m,
                            ImageUrl = "/images/products/headphones.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Wireless Headphones",
                            Price = 149.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Feature-rich smartwatch with health tracking",
                            ImageUrl = "/images/products/smartwatch.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Smart Watch",
                            Price = 299.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic aluminum laptop stand",
                            DiscountPrice = 39.99m,
                            ImageUrl = "/images/products/laptopstand.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Laptop Stand",
                            Price = 49.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable waterproof Bluetooth speaker with 20-hour battery life",
                            DiscountPrice = 59.99m,
                            ImageUrl = "/images/products/speaker.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Bluetooth Speaker",
                            Price = 79.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "7-in-1 USB-C multiport adapter with HDMI and Ethernet",
                            ImageUrl = "/images/products/usbhub.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "USB-C Hub",
                            Price = 45.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "RGB mechanical gaming keyboard with Cherry MX switches",
                            DiscountPrice = 99.99m,
                            ImageUrl = "/images/products/keyboard.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Mechanical Keyboard",
                            Price = 129.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic wireless mouse with adjustable DPI",
                            ImageUrl = "/images/products/mouse.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Wireless Mouse",
                            Price = 34.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultra HD webcam with auto-focus and built-in microphone",
                            DiscountPrice = 74.99m,
                            ImageUrl = "/images/products/webcam.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "4K Webcam",
                            Price = 89.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "20000mAh fast-charging power bank with dual USB output",
                            ImageUrl = "/images/products/charger.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Portable Charger",
                            Price = 39.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "True wireless earbuds with active noise cancellation and transparency mode",
                            DiscountPrice = 159.99m,
                            ImageUrl = "/images/products/earbuds.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Noise-Cancelling Earbuds",
                            Price = 199.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cotton casual shirt for everyday wear",
                            ImageUrl = "/images/products/shirt.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Men's Casual Shirt",
                            Price = 39.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant summer dress with floral print",
                            DiscountPrice = 44.99m,
                            ImageUrl = "/images/products/dress.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Women's Summer Dress",
                            Price = 59.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic blue denim jacket with button closure",
                            DiscountPrice = 69.99m,
                            ImageUrl = "/images/products/denimjacket.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Denim Jacket",
                            Price = 89.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight breathable running shoes with gel cushioning",
                            DiscountPrice = 94.99m,
                            ImageUrl = "/images/products/sneakers.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Running Sneakers",
                            Price = 119.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft merino wool scarf for cold weather",
                            ImageUrl = "/images/products/scarf.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Wool Scarf",
                            Price = 29.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genuine leather belt with brushed metal buckle",
                            ImageUrl = "/images/products/belt.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Leather Belt",
                            Price = 34.99m,
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic fit polo shirt in assorted colors",
                            DiscountPrice = 34.99m,
                            ImageUrl = "/images/products/polo.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Cotton Polo Shirt",
                            Price = 44.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stretch chino pants with modern slim fit",
                            ImageUrl = "/images/products/chinos.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Slim Fit Chinos",
                            Price = 54.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Insulated waterproof parka with faux fur hood",
                            DiscountPrice = 139.99m,
                            ImageUrl = "/images/products/parka.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Winter Parka",
                            Price = 179.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "UV400 polarized sunglasses with metal frame",
                            ImageUrl = "/images/products/sunglasses.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Sunglasses",
                            Price = 24.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comprehensive guide to C# programming",
                            ImageUrl = "/images/products/csharpbook.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Programming in C#",
                            Price = 44.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern web design principles and practices",
                            ImageUrl = "/images/products/webdesignbook.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "The Art of Web Design",
                            Price = 34.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A handbook of agile software craftsmanship by Robert C. Martin",
                            DiscountPrice = 29.99m,
                            ImageUrl = "/images/products/cleancode.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Clean Code",
                            Price = 39.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elements of reusable object-oriented software",
                            ImageUrl = "/images/products/designpatterns.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Design Patterns",
                            Price = 49.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "In-depth guide to data structures and algorithms in Python",
                            DiscountPrice = 34.99m,
                            ImageUrl = "/images/products/dsabook.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Data Structures & Algorithms",
                            Price = 42.99m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Your journey to mastery — 20th anniversary edition",
                            ImageUrl = "/images/products/pragmatic.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "The Pragmatic Programmer",
                            Price = 46.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A modern approach to artificial intelligence fundamentals",
                            DiscountPrice = 44.99m,
                            ImageUrl = "/images/products/aibook.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Introduction to AI",
                            Price = 54.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete guide to database design and SQL",
                            ImageUrl = "/images/products/databasebook.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Database Systems",
                            Price = 38.99m,
                            StockQuantity = 160
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "From beginner to professional JavaScript developer",
                            DiscountPrice = 24.99m,
                            ImageUrl = "/images/products/jsbook.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Learning JavaScript",
                            Price = 32.99m,
                            StockQuantity = 170
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mastering AWS, Azure, and Google Cloud platforms",
                            ImageUrl = "/images/products/cloudbook.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Cloud Computing Essentials",
                            Price = 48.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set of 3 modern ceramic plant pots with drainage holes",
                            DiscountPrice = 27.99m,
                            ImageUrl = "/images/products/plantpots.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Ceramic Plant Pot Set",
                            Price = 34.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable LED desk lamp with 5 brightness levels and USB charging",
                            ImageUrl = "/images/products/desklamp.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "LED Desk Lamp",
                            Price = 44.99m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultra-soft fleece throw blanket 150x200cm",
                            DiscountPrice = 22.99m,
                            ImageUrl = "/images/products/blanket.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Throw Blanket",
                            Price = 29.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Abstract wall art canvas print set — 3 panels",
                            ImageUrl = "/images/products/wallart.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Wall Art Canvas",
                            Price = 64.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5-piece stainless steel garden tool kit with carrying bag",
                            DiscountPrice = 34.99m,
                            ImageUrl = "/images/products/gardentools.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Garden Tool Set",
                            Price = 42.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set of 4 soy wax scented candles — lavender, vanilla, rose, cedar",
                            ImageUrl = "/images/products/candles.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Scented Candle Collection",
                            Price = 24.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "3-tier stainless steel kitchen spice and utensil organizer",
                            DiscountPrice = 31.99m,
                            ImageUrl = "/images/products/organizer.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Kitchen Organizer Rack",
                            Price = 39.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set of 4 linen cushion covers with geometric patterns",
                            ImageUrl = "/images/products/cushions.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Decorative Cushion Covers",
                            Price = 19.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pack of 8 waterproof LED solar pathway lights",
                            DiscountPrice = 26.99m,
                            ImageUrl = "/images/products/solarlights.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Solar Garden Lights",
                            Price = 32.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Self-watering indoor herb garden with basil, mint, and parsley seeds",
                            ImageUrl = "/images/products/herbgarden.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Indoor Herb Garden Kit",
                            Price = 27.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-slip eco-friendly TPE yoga mat 6mm thick",
                            DiscountPrice = 22.99m,
                            ImageUrl = "/images/products/yogamat.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Yoga Mat",
                            Price = 29.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pair of adjustable dumbbells 5–25 kg with quick-lock system",
                            DiscountPrice = 169.99m,
                            ImageUrl = "/images/products/dumbbells.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Adjustable Dumbbells",
                            Price = 199.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set of 5 resistance bands with different tension levels",
                            ImageUrl = "/images/products/bands.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Resistance Bands Set",
                            Price = 19.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1-liter insulated stainless steel water bottle",
                            ImageUrl = "/images/products/waterbottle.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Sports Water Bottle",
                            Price = 24.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Speed jump rope with ball bearings and adjustable length",
                            DiscountPrice = 11.99m,
                            ImageUrl = "/images/products/jumprope.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Jump Rope",
                            Price = 14.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-density foam roller for muscle recovery — 45cm",
                            ImageUrl = "/images/products/foamroller.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Foam Roller",
                            Price = 24.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official size 7 indoor/outdoor composite leather basketball",
                            DiscountPrice = 28.99m,
                            ImageUrl = "/images/products/basketball.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Basketball",
                            Price = 34.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight graphite tennis racket with vibration dampener",
                            ImageUrl = "/images/products/tennisracket.png",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Tennis Racket",
                            Price = 89.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Waterproof fitness tracker with heart-rate monitor and sleep tracking",
                            DiscountPrice = 39.99m,
                            ImageUrl = "/images/products/fitnesstracker.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Fitness Tracker Band",
                            Price = 49.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "50L waterproof hiking backpack with multiple compartments",
                            DiscountPrice = 59.99m,
                            ImageUrl = "/images/products/backpack.png",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Camping Backpack",
                            Price = 74.99m,
                            StockQuantity = 55
                        });
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("StoreWave.Models.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("StoreWave.Models.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreWave.Models.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("StoreWave.Models.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreWave.Models.Entities.CartItem", b =>
                {
                    b.HasOne("StoreWave.Models.Entities.Customer", "Customer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreWave.Models.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("StoreWave.Models.Entities.Order", "Order")
                        .WithMany("ChatMessages")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreWave.Models.Entities.Customer", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Order", b =>
                {
                    b.HasOne("StoreWave.Models.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoreWave.Models.Entities.Customer", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("StoreWave.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreWave.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Product", b =>
                {
                    b.HasOne("StoreWave.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoreWave.Models.Entities.Customer", "Supplier")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Review", b =>
                {
                    b.HasOne("StoreWave.Models.Entities.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoreWave.Models.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Customer", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Order", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("StoreWave.Models.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
